package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "github.com/digitalmaxing/devices-api/docs" // swagger docs generated by swag

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/digitalmaxing/devices-api/internal/config"
	"github.com/digitalmaxing/devices-api/internal/handlers"
	"github.com/digitalmaxing/devices-api/internal/models"
	"github.com/digitalmaxing/devices-api/internal/repository"
	"github.com/digitalmaxing/devices-api/internal/service"
)

// @title Devices API
// @version 1.0
// @description REST API for persisting and managing device resources. Supports full CRUD, filtering, and enforces business rules around device states.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.url https://github.com/digitalmaxing/devices-api/issues
// @license.name MIT
// @license.url https://opensource.org/licenses/MIT
// @host localhost:8080
// @BasePath /
// @schemes http
func main() {
	cfg := config.Load()

	// Establish database connection
	db, err := gorm.Open(postgres.Open(cfg.GetDBDSN()), &gorm.Config{
		// Add any GORM config like logger here if needed
	})
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	// Auto-migrate schema (for development; use proper migrations in production)
	if err := db.AutoMigrate(&models.Device{}); err != nil {
		log.Fatalf("Failed to migrate database: %v", err)
	}

	// Dependency injection: repo -> service -> handler
	repo := repository.NewPostgresDeviceRepository(db)
	svc := service.NewDeviceService(repo)
	deviceHandler := handlers.NewDeviceHandler(svc)

	// Initialize Gin router (release mode in prod via env)
	if os.Getenv("GIN_MODE") == "release" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.Default()

	// Swagger UI endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Health check for container orchestration / k8s
	r.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "healthy", "service": "devices-api"})
	})

	// API routes group
	api := r.Group("/devices")
	{
		api.POST("", deviceHandler.CreateDevice)
		api.GET("", deviceHandler.ListDevices)
		api.GET("/:id", deviceHandler.GetDevice)
		api.PATCH("/:id", deviceHandler.UpdateDevice)
		api.DELETE("/:id", deviceHandler.DeleteDevice)
	}

	log.Printf("🚀 Devices API starting on %s | DB: %s:%s | Swagger: http://localhost:%s/swagger/index.html",
		cfg.GetServerAddr(), cfg.DBHost, cfg.DBPort, cfg.ServerPort)

	if err := r.Run(cfg.GetServerAddr()); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}